trigger:
  branches:
    include:
      - main
pool:
  name: Default

variables:
  - group: docker_vars
  - name: imageName
    value: feedback-app
  - name: imageTag
    value: $(Build.BuildId)
  
parameters:
  - name: environment
    displayName: Environment
    type: string
    default: dev
    values:
      - dev
      - prod
stages:

- stage: CI
  displayName: CI stage
  jobs:
  - job: backend
    steps:
    - checkout: self
    - script: |
       sudo yum install python3.9 -y
      displayName: 'Install Python 3.9'
    - script: |
        sudo yum install python3-pip -y
        sudo python -m pip install --upgrade pip
        sudo pip install flask pytest flake8
        sudo pip install pytest
      displayName: 'Install Flask and linting tools'
    - script: flake8 src/feedback_backend/app.py
      displayName: Linting Backend
    - script: |
        python3 -m pytest src/tests/test_app.py
      displayName: 'Run Backend Tests'
      
  - job: docker
    dependsOn: backend
    displayName: docker build
    steps:
    - checkout: self
    - script: |
        sudo yum install -y yum-utils
        sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        sudo yum install -y docker-ce docker-ce-cli containerd.io
        sudo systemctl start docker
        sudo systemctl enable docker
        sudo usermod -aG docker $USER
      displayName: 'Install Docker'

    - task: Docker@2
      condition: succeeded()
      displayName: 'Build frontend image'
      inputs:
        containerRegistry: 'dockerHubConnection'
        repository: '$(DOCKER_USERNAME)/$(imageName)-frontend'
        command: 'buildAndPush'
        Dockerfile: 'src/feedback_frontend/src/Dockerfile'
        tags: |
          $(Build.BuildId)
    - task: Docker@2
      displayName: 'Build backend image'
      condition: succeeded()
      inputs:
        containerRegistry: 'dockerHubConnection'
        repository: '$(DOCKER_USERNAME)/$(imageName)-backend'
        command: 'buildAndPush'
        Dockerfile: 'src/feedback_backend/Dockerfile'
        tags: |
          $(Build.BuildId)
    
      
