trigger:
  branches:
    include:
      - main
pool:
  name: Default

variables:
  - group: docker_vars
  - name: imageName
    value: feedback-app
  - name: imageTag
    value: $(Build.BuildId)
  
parameters:
  - name: environment
    displayName: environment
    type: string
    default: dev
    values:
      - dev
stages:
- stage: CD
  displayName: CD stage
  jobs:
  - deployment: deployToDev
    displayName: Deploy to ${{ parameters.environment }} EKS
    environment: '${{ parameters.environment }}'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: ReplaceTokens@5
            displayName: 'Replace tokens in Kubernetes YAML'
            inputs:
              rootDirectory: '$(System.DefaultWorkingDirectory)'        
              targetFiles: 'k8s/*.yaml'
              tokenPrefix: '${'
              tokenSuffix: '}'
              escapeType: 'json'
              verbosity: 'detailed'
            env:  # Explicitly pass variables (optional but recommended)
              DOCKER_USERNAME: $(DOCKER_USERNAME)
              IMAGE_NAME: $(imageName)
              IMAGE_TAG: $(imageTag)
          - task: AWSShellScript@1
            displayName: 'Update kubeconfig'
            inputs:
              awsCredentials: 'aws-credentials'
              regionName: 'us-east-1'
              scriptType: 'inline'
              inlineScript: |
                 aws eks update-kubeconfig --name my-eks-cluster --region us-east-1 
          - script: |
              kubectl create namespace ${{ parameters.environment }}
              kubectl Replace -f k8s/ -n ${{ parameters.environment }} --force
            displayName: 'Deploy to EKS'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
              
