trigger:
  branches:
    include:
      - main
pool:
  name: Default
variables:
  - group: docker_vars
  - group: jfrog-helm-repo
  - name: imageName
    value: note-app
  - name: imageTag
    value: $(Build.BuildId)
  
parameters:
  - name: environment
    displayName: environment
    type: string
    default: dev
    values:
      - dev
stages:
- stage: prerequest
  displayName: 'pre-request stage'
  jobs:
    - job: prerequest
      displayName: pre-request job
      steps:
       - checkout: self
       - script: |
            ansible-playbook -i ansible/inventory ansible/Playbook.yml
         workingDirectory: '$(System.DefaultWorkingDirectory)'
         displayName: 'Run Ansible Playbook to install dependencies'
          
- stage: CI
  displayName: CI stage
  dependsOn: prerequest
  jobs:
  - job: test
    steps:
    - checkout: self
    - script: flake8 src/note_backend/app.py
      displayName: Linting Backend
    - script: |
        sudo pip install -r src/note_backend/requirements.txt
        python3 -m pytest tests/test_app.py  --cov=src/note_backend --cov-report=xml
      displayName: 'Run Backend Tests'
  - job: sonarqube
    dependsOn: test
    timeoutInMinutes: 20
    steps:
    - checkout: self
      fetchDepth: 0
    - script: |
        export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
        echo "##vso[task.setvariable variable=JAVA_HOME]$JAVA_HOME"
        echo "JAVA_HOME set to $JAVA_HOME"
        java -version
      displayName: 'Install Java 17'
    - task: SonarCloudPrepare@3
      displayName: 'Configure SonarCloud Analysis'
      inputs:
        SonarQube: 'sonarservice'
        organization: 'ashouryasser11'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'ashouryasser11_note-app-DevSecOps.git'
        cliProjectName: 'note-app-DevSecOps'
        extraProperties: |
          sonar.sources=src/note_backend
          sonar.python.coverage.reportPaths=$(System.DefaultWorkingDirectory)/coverage.xml
          sonar.exclusions=**/tests/**
          sonar.python.version=3.9
    - task: SonarCloudAnalyze@3
      displayName: 'Run SonarCloud Analysis'
    - task: SonarCloudPublish@3
      displayName: 'Publish Quality Gate Results'
  - job: docker
    dependsOn: sonarqube
    - task: Docker@2
      condition: succeeded()
      displayName: 'Build frontend image'
      inputs:
        containerRegistry: 'dockerHubConnection'
        repository: '$(DOCKER_USERNAME)/$(imageName)-frontend'
        command: 'buildAndPush'
        buildContext: '$(System.DefaultWorkingDirectory)'
        Dockerfile: 'src/note_frontend/src/Dockerfile'
        tags: |
          $(Build.BuildId)

    - task: Docker@2
      displayName: 'Build backend image'
      inputs:
        containerRegistry: 'dockerHubConnection'
        repository: '$(DOCKER_USERNAME)/$(imageName)-backend'
        command: 'buildAndPush'
        Dockerfile: 'src/note_backend/Dockerfile'
        buildContext: '$(System.DefaultWorkingDirectory)'
        tags: |
          $(Build.BuildId)

  - job: helm
    dependsOn: docker
    displayName: build HELM Chart
    steps:
    - checkout: self
    
    - task: Bash@3
      displayName: 'replace image tags in helm chart'
      inputs:
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        targetType: 'inline'
        script: |
          sed -i "s|{DOCKER_USERNAME}-frontend|$(DOCKER_USERNAME)/$(imageName)-frontend:$(Build.BuildId)|g" note-chart/values.yaml
          sed -i "s|{DOCKER_USERNAME}-backend|$(DOCKER_USERNAME)/$(imageName)-backend:$(Build.BuildId)|g" note-chart/values.yaml
          echo "Updated values.yaml:"
          grep -A 1 "image:" note-chart/values.yaml

    - task: Bash@3
      displayName: 'build helm chart'
      inputs:
        targetType: 'inline'
        script: |
          helm package note-chart --version 0.1.$(Build.BuildId) --app-version 1.0.$(Build.BuildId)
          curl -u "$(helm_repo_user):$(helm_repo_token)" -X PUT \
               -T note-chart-0.1.$(Build.BuildId).tgz \
               "$(repository)/note-chart-0.1.$(Build.BuildId).tgz"
    - task: Bash@3
      displayName: 'helm repo index'
      inputs:
        targetType: 'inline'
        script: |
          helm repo add my_repo $(repository) --username $(helm_repo_user) --password $(helm_repo_token)
          helm repo update
    - task: Bash@3
      displayName: 'Check Helm Chart Version'
      inputs:
        targetType: 'inline'
        script: |
          echo "Running Helm template..."
          CHART_NAME="my_repo/note-chart"        
          EXPECTED_VERSION="0.1.$(Build.BuildId)"
          echo "Expected version: $EXPECTED_VERSION"
          SEARCH_RESULT=$(helm search repo $CHART_NAME --version $EXPECTED_VERSION)

          if echo "$SEARCH_RESULT" | grep -q "$EXPECTED_VERSION"; then
             echo "Chart version $EXPECTED_VERSION exists"
          else
            echo "Chart version $EXPECTED_VERSION does NOT exist"
            exit 1
          fi

- stage: CD
  displayName: CD stage
  jobs:
  - deployment: deployToDev
    displayName: Deploy to ${{ parameters.environment }} EKS
    environment: '${{ parameters.environment }}'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
         # - task: ReplaceTokens@6
          ## inputs:
             # rootDirectory: '$(System.DefaultWorkingDirectory)'        
             # targetFiles: 'k8s/*.yaml'
             # tokenPrefix: '${'
             # tokenSuffix: '}'
             # escapeType: 'json'
             # verbosity: 'detailed'
          - task: AWSShellScript@1
            displayName: 'Update kubeconfig'
            inputs:
              awsCredentials: 'aws-credentials'
              regionName: 'us-east-1'
              scriptType: 'inline'
              inlineScript: |
                 aws eks update-kubeconfig --name my-eks-cluster --region us-east-1 
  
          - task: Bash@3
            displayName: 'helm install'
            condition: succeeded()
            inputs:
              targetType: 'inline'
              script: |
                helm  upgrade --install note-chart note-chart/my_repo --version 0.1.$(Build.BuildId)