trigger:
  branches:
    include:
      - main
pool:
  name: Default

variables:
  - group: docker_vars
  - name: imageName
    value: feedback-app
  - name: imageTag
    value: $(Build.BuildId)
  
parameters:
  - name: environment
    displayName: environment
    type: string
    default: ASH-env
    values:
      - ASH-env
stages:

- stage: CD
  jobs:
  - deployment: deployToDev
    displayName: Deploy to ${{ parameters.environment }} EKS
    environment: '${{ parameters.environment }}'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: ReplaceTokens@5
            displayName: 'Replace tokens in Kubernetes YAML'
            inputs:
              rootDirectory: '$(System.DefaultWorkingDirectory)'        
              targetFiles: 'k8s/*.yaml'
              tokenPrefix: '${'
              tokenSuffix: '}'
              escapeType: 'json'
              verbosity: 'detailed'

          - task: AWSShellScript@1
            displayName: 'Update kubeconfig'
            inputs:
              awsCredentials: 'aws-credentials'
              regionName: 'us-east-1'
              scriptType: 'inline'
              inlineScript: |
                 aws eks update-kubeconfig --name feedback-cluster --region us-east-1 
          - script: |
              kubectl apply -f $(Build.SourceDirectory)/k8s/ -n ${{ parameters.environment }}
            displayName: 'Deploy to EKS'
              
