trigger:
  branches:
    include:
      - main

pool:
  name: Default

stages:

- stage: CI
  displayName: CI stage
  jobs:
  - job: Lint
    displayName: Linting Backend
    steps:
    - checkout: self

    - script: echo "heloo"
      displayName: 'Install Terraform'

- stage: terraform_aws
  jobs:
    - job: Terraform
      variables:
        aws_access_key_id: "AWS_ACCESS_KEY_ID:"
        aws_secret_access_key: "AWS_ACCESS_KEY_ID:"
        aws_session_token: "AWS_ACCESS_KEY_ID:"
      steps:
        - checkout: self
        - script: |
             sudo yum install -y yum-utils
             sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
             sudo yum -y install terraform
          displayName: 'Install Terraform and aws cradintiasls'
          env:
            AWS_ACCESS_KEY_ID: $(aws_access_key_id)
            AWS_SECRET_ACCESS_KEY: $(aws_secret_access_key)
            AWS_SESSION_TOKEN: $(aws_session_token)
          condition: succeeded()

        - script: |
             echo "Checking AWS credentials..."
             echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
             echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
             echo "AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN"
          displayName: 'Check AWS Credentials'
          condition: succeeded()

        - script: terraform fmt
          displayName: 'Terraform Format'
          condition: succeeded()

        - script: terraform init
          displayName: 'Terraform Init'
          condition: succeeded()

        - script: terraform plan -out=tfplan
          displayName: 'Terraform Plan'
          condition: succeeded()

        - script: terraform apply -auto-approve tfplan
          displayName: 'Terraform Apply'
          condition: succeeded()
   
