trigger:
  branches:
    include:
      - main

pool:
  name: Default

stages:

- stage: CI
  displayName: CI stage
  jobs:
  - job: Lint
    displayName: Linting Backend
    steps:
    - checkout: self

    - script: echo "heloo"
      displayName: 'Install Terraform'

- stage: TerraformCLI
  jobs:
    - job: Terraform
      steps:
        - checkout: self

        - script: sudo yum install -y terraform
          displayName: 'Install Terraform'

        - script: terraform init
          displayName: 'Terraform Init'
          condition: succeeded()

        - script: terraform plan -out=tfplan
          displayName: 'Terraform Plan'
          condition: succeeded()

        - script: terraform apply -auto-approve tfplan
          displayName: 'Terraform Apply'
          condition: succeeded()
