trigger:
  branches:
    include:
      - main
pool:
  name: Default
stages:

- stage: CI
  displayName: CI stage
  jobs:
  - job: backend
    steps:
    - checkout: self

    - script: echo "heloo"
      displayName: Linting Backend

    - script: echo "heloo"
      displayName: 'Test backend'

  - job: frontend
    displayName: Linting frontend

    steps:
    - checkout: self

    - script: echo "heloo"
      displayName: 'Test frontend'