# Feedback application

trigger:
    branches:
      include:
        - main

pool:
    name: Default
stages:

- stage: CI
  displayName: CI stage
  jobs:
  - job: Lint
    displayName: Linting Backend
    steps:
    - checkout: self

    - script: echo "heloo"
      displayName: 'Install Terraform'
      

  


