apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql: |
    CREATE DATABASE note;

    \connect note;

    CREATE TABLE messages (
        id SERIAL PRIMARY KEY,
        text TEXT
    );