apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.names.back }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.names.back }}
  template:
    metadata:
      labels:
        app: {{ .Values.names.back }}
    spec:
      containers:
      - name: {{ .Values.names.back }}
        image: {{ .Values.image.back }}
        ports:
        - containerPort: {{ .Values.port.back.port }}
        env:
        - name: DB_HOST
          value: postgres-service
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names.back }}-{{.Values.service}}
spec:
  selector:
    app: {{ .Values.names.back }}
  ports:
    - port: {{ .Values.port.back.port }}
