apiVersion: v2
name: note-chart
description: A Helm chart for Kubernetes deployment
type: application
version: 0.1.1         
appVersion: "1.0.1"
maintainers:
  - name: Ashour
    email: ashouryasser11@gmail.com